In [8]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn import preprocessing
from sklearn.preprocessing import LabelEncoder
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report, confusion_matrix 
from sklearn import metrics

import warnings
warnings.filterwarnings("ignore")

import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline  

In [9]:
df = pd.read_csv("FeatureSetFastBrian.csv")
df = df[df.name != "name"]
df.columns

Index(['name', 'SDx', 'SDy', 'SDz', 'SR', 'PFD_t', 'PFD_i', 'PFD_m', 'PFD_r',
       'PFD_p', 'FA_ti', 'FA_im', 'FA_mr', 'FA_rp', 'FA_pt', 'FD_ti', 'FD_tm',
       'FD_tr', 'FD_tp', 'FD_im', 'FD_ir', 'FD_ip', 'FD_mr', 'FD_mp', 'FD_rp'],
      dtype='object')

In [10]:
createLabels = pd.DataFrame(df,columns=['name'])
createLabels.rename(columns={'name':'0'},inplace = True)
for index,row in createLabels.iterrows():
    createLabels.set_value(index,'0',row['0'][0])
createLabels.to_csv("labelsForTestAndTrainFastBrian.csv")

In [11]:
le = preprocessing.LabelEncoder()
le.fit(createLabels['0'])
LabelEncoder()
list(le.classes_)

letter_mappings = dict()
# create csv of letter to label mappings
for i in range(0, len(le.classes_)):
    letter_mappings[le.classes_[i]] = i
letter_mappings

{'A': 0,
 'B': 1,
 'C': 2,
 'D': 3,
 'E': 4,
 'F': 5,
 'G': 6,
 'H': 7,
 'I': 8,
 'K': 9,
 'L': 10,
 'M': 11,
 'N': 12,
 'O': 13,
 'P': 14,
 'R': 15,
 'S': 16,
 'T': 17,
 'U': 18,
 'V': 19,
 'W': 20,
 'X': 21,
 'Y': 22}

In [12]:
transformedLabels = le.transform(createLabels['0']) 
np.unique(transformedLabels)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22])

In [13]:
df['labels'] = transformedLabels
df

name SDx SDy SDz         SR        PFD_t        PFD_i        PFD_m  \
0        A   0   0   0  36.474487   62.1613121  41.63286972  40.62351227   
1        A   0   0   0  36.524467  62.20118332  41.63124084    40.668293   
2        A   0   0   0   36.88997  62.54512787  41.51000977  40.53670883   
3        A   0   0   0  36.866932   62.5332756  41.52760315  40.55209732   
4        A   0   0   0  36.866932   62.5332756  41.52760315  40.55209732   
5        A   0   0   0   36.83379  62.51315689  41.54090118  40.56211853   
6        A   0   0   0  36.797794  62.48514557  41.54735565  40.56980515   
7        A   0   0   0  36.750824  62.43977737  41.54794693  40.57364273   
8        A   0   0   0  36.750824  62.43977737  41.54794693  40.57364273   
9        A   0   0   0   36.51352  62.32382965  41.55205154  40.60037231   
10       A   0   0   0  36.484146  62.29518509  41.55183029  40.60792542   
11       A   0   0   0  36.484146  62.29518509  41.55183029  40.60792542   
12       A   0   0   0  36.462566  62.27332306  41.55310822  40.61485672   
13       A   0   0   0  36.441628  62.24765015  41.55354309  40.61893845   
14       A   0   0   0  36.424915  62.21846771  41.55830383  40.62414932   
15       A   0   0   0  36.414436  62.18638229   41.5647316   40.6273613   
16       A   0   0   0  36.414436  62.18638229   41.5647316   40.6273613   
17       A   0   0   0    36.4097  62.16229248  41.56590652  40.62483215   
18       A   0   0   0   36.41147   62.1499939  41.56875992  40.62031937   
19       A   0   0   0   36.41147   62.1499939  41.56875992  40.62031937   
20       A   0   0   0  36.416378  62.13654327  41.57212448  40.61964798   
21       A   0   0   0  36.427887  62.12794495  41.57735062  40.61923218   
22       A   0   0   0  36.427887  62.12794495  41.57735062  40.61923218   
23       A   0   0   0  36.437984  62.12516785  41.57926178  40.61626434   
24       A   0   0   0  36.442867  62.11354065  41.58124924  40.61352539   
25       A   0   0   0  36.444096  62.10261154  41.58450699  40.60804749   
26       A   0   0   0  36.416622  62.04503632  41.59128189  40.60577774   
27       A   0   0   0   36.39469  62.01436996  41.59822845  40.61220169   
28       A   0   0   0   36.39469  62.01436996  41.59822845  40.61220169   
29       A   0   0   0  36.366913  61.98290634   41.6086235  40.62718964   
...    ...  ..  ..  ..        ...          ...          ...          ...   
25622    P   0   0   0   32.02593  64.67835999  61.10596466  40.64960861   
25623    P   0   0   0  32.038216  64.66091156  61.12622452    40.656147   
25624    P   0   0   0  32.052933  64.64833832  61.17635727  40.66270065   
25625    P   0   0   0  32.052933  64.64833832  61.17635727  40.66270065   
25626    P   0   0   0  32.070515  64.63393402  61.25555801   40.6775322   
25627    P   0   0   0  32.070515  64.63393402  61.25555801   40.6775322   
25628    P   0   0   0  32.086807  64.60705566  61.33889008  40.69704056   
25629    P   0   0   0  32.086807  64.60705566  61.33889008  40.69704056   
25630    P   0   0   0  32.098667  64.58310699  61.38343811  40.71818161   
25631    P   0   0   0   32.10663   64.5561142   61.4256134   40.7336731   
25632    P   0   0   0   32.10663   64.5561142   61.4256134   40.7336731   
25633    P   0   0   0    32.1207  64.51837158  61.50600433  40.75071716   
25634    P   0   0   0    32.1207  64.51837158  61.50600433  40.75071716   
25635    P   0   0   0  32.133297  64.47468567  61.58070374  40.77041245   
25636    P   0   0   0  32.133297  64.47468567  61.58070374  40.77041245   
25637    P   0   0   0  32.144863   64.4420929  61.60948563  40.78870392   
25638    P   0   0   0  32.152008  64.41847229  61.61371994  40.80395508   
25639    P   0   0   0  32.152008  64.41847229  61.61371994  40.80395508   
25640    P   0   0   0  32.154755   64.3969574  61.60933304   40.8197403   
25641    P   0   0   0  32.152508   64.3704071   61.5679512  40.82128906   
25642    P   0   0   0  32.152508   64.3704071   61.56

# SVM

In [14]:
df = df.drop(columns=['name'])

In [15]:
df = df.apply(pd.to_numeric, errors='coerce')

In [16]:
X = df.drop('labels', axis=1)  
y = df['labels']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.30)  

In [17]:
svclassifier = SVC(kernel='poly',degree=10)  

In [18]:
svclassifier.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=10, gamma='auto_deprecated',
  kernel='poly', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [19]:
y_pred = svclassifier.predict(X_test)  
y_pred

array([18, 19,  3, ..., 18, 11,  3])

In [20]:
metrics.accuracy_score(y_pred,y_test)

1.0

In [27]:
###Testing on new data (entire alphabet)
dfTest4 = pd.read_csv("TestBrian.csv")
dfTest4 = dfTest4[dfTest4.name != "name"]


labelsForTest4 = pd.DataFrame(dfTest4,columns=['name'])
labelsForTest4.rename(columns={'name':'0'},inplace = True)
for index,row in labelsForTest4.iterrows():
    labelsForTest4.set_value(index,'0',row['0'][0])
labelsForTest4.to_csv("labelsForTest4.csv")

dfTest4 = dfTest4.drop(columns=['name'])
dfTest4 = dfTest4.apply(pd.to_numeric, errors='coerce')

dfTest4

SDx  SDy  SDz         SR       PFD_t       PFD_i      PFD_m      PFD_r  \
0      0    0    0  45.224316   96.631470  103.438042  96.316101  79.048698   
1      0    0    0  45.457638   96.848206  103.449722  96.474457  78.860344   
2      0    0    0  46.089264   97.027649  103.527069  96.430580  78.446442   
3      0    0    0  49.056805   97.216454  103.493927  96.482117  78.127327   
4      0    0    0  46.440716   97.119835  103.475807  96.402885  78.117363   
5      0    0    0  45.590725   96.979126  103.434761  96.354782  78.282036   
6      0    0    0  46.460160   96.968384  103.369598  96.381058  78.315819   
7      0    0    0  46.460160   96.968384  103.369598  96.381058  78.315819   
8      0    0    0  45.726420   96.858650  103.356056  96.346504  78.459709   
9      0    0    0  46.997830   97.068718  103.413895  96.428658  78.285179   
10     0    0    0  45.452540   96.983101  103.406311  96.367783  78.309944   
11     0    0    0  46.210884   97.188904  103.484428  96.483002  78.113701   
12     0    0    0  45.240814   97.089096  103.482109  96.427994  78.184235   
13     0    0    0  45.218483   97.200623  103.606888  96.502731  77.933868   
14     0    0    0  46.074802   97.392609  103.640175  96.605598  77.693726   
15     0    0    0  46.283417   97.521935  103.738983  96.659225  77.357483   
16     0    0    0  45.291866   97.400963  103.728806  96.569077  77.585419   
17     0    0    0  45.523910   97.503632  103.850815  96.642380  77.454948   
18     0    0    0  45.523910   97.503632  103.850815  96.642380  77.454948   
19     0    0    0  47.119030   97.406647  103.839554  96.573143  77.777336   
20     0    0    0  49.170734   97.298050  103.829231  96.535622  78.086868   
21     0    0    0  51.323334   97.210861  103.815407  96.504517  78.380493   
22     0    0    0  49.883728   97.456177  103.936836  96.626739  78.206947   
23     0    0    0  49.883728   97.456177  103.936836  96.626739  78.206947   
24     0    0    0  49.334106   97.629074  104.015274  96.662575  77.900436   
25     0    0    0  48.779240   97.720680  104.031578  96.665291  77.572601   
26     0    0    0  46.169483   97.892853  103.974182  96.625534  76.749382   
27     0    0    0  46.097230   97.837456  103.890472  96.539665  76.479889   
28     0    0    0  50.170567   97.799202  104.061089  96.578850  76.104866   
29     0    0    0  50.170567   97.799202  104.061089  96.578850  76.104866   
..   ...  ...  ...        ...         ...         ...        ...        ...   
173    0    0    0  58.295883  100.163734   89.890800  39.712708  37.953571   
174    0    0    0  58.273186  100.147827   89.872810  39.698555  37.949898   
175    0    0    0  58.273186  100.147827   89.872810  39.698555  37.949898   
176    0    0    0  58.280945   99.980675   89.893547  39.917110  38.220108   
177    0    0    0  58.194927   99.887932   89.888496  39.943672  38.253494   
178    0    0    0  58.090360   99.791855   89.880554  39.932930  38.253891   
179    0    0    0  58.090360   99.791855   89.880554  39.932930  38.253891   
180    0    0    0  58.038586   99.761780   89.882645  39.916573  38.249687   
181    0    0    0  57.975506   99.732849   89.876686  39.917053  38.262661   
182    0    0    0  57.940945   99.724922   89.883377  39.931660  38.284096   
183    0    0    0  57.940945   99.724922   89.883377  39.931660  38.284096   
184    0    0    0  57.952103   99.589470   89.929375  40.184822  38.586506   
185    0    0    0  57.850616   99.492126   89.942345  40.233368  38.647415   
186    0    0    0  57.850616   99.492126   89.942345  40.233368  38.647415   
187    0    0    0  57.758537   99.412834   89.952339  40.248615  38.667072   
188    0    0    0  57.681220   99.359390   89.964378  40.247662  38.678825   
189    0    0    0  57.613503   99.319565   89.991470  40.248337  38.690735   
190    0    0    0  57.613503   99.319565   89.991470  40.248337  38.690735   
191    0    0    0  57.545082   99.269371   90.021187  

In [28]:
dfTest_pred4 = svclassifier.predict(dfTest4)  
transformedLabelsForTest4 = le.transform(labelsForTest4['0']) 
transformedLabelsForTest4

for i in range(len(dfTest_pred4)):
    if(i % 50 == 0 and le.classes_[i//50]  != le.classes_[dfTest_pred4[i]]):
        print(le.classes_[i//50] + " was recognized as " + le.classes_[dfTest_pred4[i]])

A was recognized as B
C was recognized as L
D was recognized as L


In [30]:
metrics.accuracy_score(dfTest_pred4,transformedLabelsForTest4)
print(confusion_matrix(dfTest_pred4,transformedLabelsForTest4))  
print(classification_report(dfTest_pred4,transformedLabelsForTest4)) 

[[100   0]
 [  0 100]]
              precision    recall  f1-score   support

           1       1.00      1.00      1.00       100
          10       1.00      1.00      1.00       100

   micro avg       1.00      1.00      1.00       200
   macro avg       1.00      1.00      1.00       200
weighted avg       1.00      1.00      1.00       200



In [ ]:
[i for i, j in zip(dfTest_pred4, transformedLabelsForTest4) if i != j]

In [23]:
from sklearn_porter import Porter
porter = Porter(svclassifier, language='java')
output = porter.export(embed_data=True)
print(output)

class SVC {

    private enum Kernel { LINEAR, POLY, RBF, SIGMOID }

    private int nClasses;
    private int nRows;
    private int[] classes;
    private double[][] vectors;
    private double[][] coefficients;
    private double[] intercepts;
    private int[] weights;
    private Kernel kernel;
    private double gamma;
    private double coef0;
    private double degree;

    public SVC (int nClasses, int nRows, double[][] vectors, double[][] coefficients, double[] intercepts, int[] weights, String kernel, double gamma, double coef0, double degree) {
        this.nClasses = nClasses;
        this.classes = new int[nClasses];
        for (int i = 0; i < nClasses; i++) {
            this.classes[i] = i;
        }
        this.nRows = nRows;

        this.vectors = vectors;
        this.coefficients = coefficients;
        this.intercepts = intercepts;
        this.weights = weights;

        this.kernel = Kernel.valueOf(kernel.toUpperCase());
        this.gamma = gamma;
        thi